name: Generate File

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags.

      - name: Cache version
        uses: actions/cache@v2
        with:
          path: ./version.ini
          key: version-${{ hashFiles('**/version.ini') }}

      - name: Read version
        id: read-version
        run: echo "::set-output name=version::$(cat version.ini)"

      - name: Check if version has changed
        id: version-check
        run: |
          git diff --exit-code --quiet HEAD..HEAD^ version.ini || echo "::set-output name=has_changed::true"

      - name: Create directory
        run: mkdir -p generated

      - name: Remove comment and Generate file
        if: steps.version-check.outputs.has_changed == 'true'
        run: |
          version="${{ steps.read-version.outputs.version }}"
          commit_sha=$(git rev-parse HEAD)
          commit_desc=$(git log -1 --pretty=%B)
          content_r=$(perl -0777 -pe 's|\s*\/\*[^\*]*(?:(?!\*\/)\*[^\*]*)*\*\/\s*||' js/content.js)
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout generated-files || git checkout -b generated-files
          git reset --hard origin/main
          echo "$content_r" > temp_content.js
          cp userscript/template.js temp_template.js
          sed -i "s/{{VERSION}}/$version/g" temp_template.js
          sed -i "s/{{COMMIT_SHA}}/$commit_sha/g" temp_template.js
          sed -i "s/{{COMMIT_SHA}}/$commit_sha/g" temp_template.js
          sed -i '/{{CONTENT}}/r temp_content.js' temp_template.js
          sed -i '/{{CONTENT}}/d' temp_template.js
          rm temp_content.js # remove the temporary file
          rm -f generated/Tabview-Youtube.user.js # use -f to ignore error if the file does not exist
          mv temp_template.js generated/Tabview-Youtube.user.js
          git add generated/Tabview-Youtube.user.js
          if git diff --exit-code --quiet --cached; then
            echo "No changes to commit"
          else
            git commit -m "v$version: Userscript Generation" -m ""$'\n\n\n\n'"$commit_desc"'\n\n'"Commit $commit_sha"
            git push -f origin generated-files
          fi
